### Create numpy arrray and print the even numbers

In [4]:
import numpy as np
nums = np.array([1,2,3,4,5,6])
print(nums[nums%2==0])

[2 4 6]


## Countries and Employment

In [18]:
countries = np.array(['Afganistan','Albania','Algeria','Angola','Argentina'])
employment = np.array([55.70,51.40,50.50,75.69,58.40])

### Slicing

In [29]:
print(countries[0]) #first index
print(countries[1:3]) #0 to 2 index
print(countries[:2]) #first to 1 index
print(countries[:]) #all values

Afganistan
['Albania' 'Algeria']
['Afganistan' 'Albania']
['Afganistan' 'Albania' 'Algeria' 'Angola' 'Argentina']


### Data Types

In [24]:
print(countries.dtype)
print(employment.dtype)

<U10
float64


### Loops and Formatting in print

In [31]:
for i in range(3):
    country = countries[i]
    country_employment = employment[i]
    print('Country {} has employment of {}'.format(country,country_employment))

print 2 and 5
Country Afganistan has employment of 55.7
Country Albania has employment of 51.4
Country Algeria has employment of 50.5


### Numpy Functions

In [40]:
print(employment.mean()) #returns the mean
print(employment.var()) #returns the variance
print(employment.std()) #returns the standard deviation
print(employment.max()) #returns the max
print(employment.min()) #returns the min
print(employment.sum()) #returns the sum
print(employment.argmax()) #returns the index of maximum

58.338
83.52497599999998
9.139199964985993
75.69
50.5
291.69
3


### roll, name, marks and print the maximum

In [65]:
roll = np.array([509,512,521,506,566])
name = np.array(["Suman Rajak","Nazlee Rahman","Sulagna Dey","Rishabh Baptish","Aman Gupta"])
marks = np.array([289,208,278,297,268])

maxmark = marks.argmax()

print("{} with roll number - {} got the highest marks - {}".format(name[maxmark],roll[maxmark],marks[maxmark]))

Rishabh Baptish with roll number - 506 got the highest marks - 297


### Vectorized Operations

### Working with vectors

In [70]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a+b)
print(a*b)

#List concatenation, note the difference of python list
print([1,2,3]+[4,5,6])

#multiplying by a scalar
print(a*3)
#in python list
print([1,2,3]*3)

[5 7 9]
[ 4 10 18]
[1, 2, 3, 4, 5, 6]
[3 6 9]
[1, 2, 3, 1, 2, 3, 1, 2, 3]


### Logical operations

In [73]:
a = np.array([True,True,False,False])
b = np.array([True,False,True,False])
print(a&b)
print(~a)
print(a&False)

[ True False False False]
[False False  True  True]
[False False False False]


### Comparison between two arrays

In [82]:
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])
print(a>b)

[False False False  True  True]


### Comparison with a scalar value

In [84]:
print(a>2)

[False False  True  True  True]


In [101]:
a = np.array([1,2,3,4])
b = np.array([True,True,False,False])
print(a[b])
print(a[a>2])
print(len(a[a>2]))

[1 2]
[3 4]
2


### Creating index array using vector operations

In [107]:
b = a>2
print(b)
print(b.mean())

[False False False  True]
0.25


### Incrementation and Assignment

In [136]:
# a and b both refer to the same array
a = np.array([1,2,3])
b = a
a += 1
print(b)

[2 3 4]


In [138]:
# a is later reassigned which creates a new array. then a refers to a new array while b refers to the original array
a = np.array([1,2,3])
b = a
a = a+1
print(b)

[1 2 3]


### Slicing

In [143]:
# Take a slice, Numpy does not create a new array.
a = np.array([1,2,3,4])
slice = a[:3]
slice[0] = 10
print(a)

[10  2  3  4]


In [145]:
# Try python list
a = [1,2,3,4]
slice = a[:3]
slice[0] = 10
print(a)

[1, 2, 3, 4]


### Two dimensional data

In [175]:
twod = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("\n",twod)
print("\n",twod[1,3])
print("\n",twod[0:2,0:2])


 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 8

 [[1 2]
 [5 6]]
