In [9]:
import numpy as np

### Axis Value

In [29]:
twod = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
twod1 = np.array([[2,3,4,5],[6,7,8,9],[1,2,3,4]])
print(twod)
print(twod1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3 4 5]
 [6 7 8 9]
 [1 2 3 4]]


In [12]:
twod.mean(axis=0)

array([5., 6., 7., 8.])

In [13]:
twod.mean(axis = 1)

array([ 2.5,  6.5, 10.5])

### Sum of two 2d matrices

In [33]:
print("Sum = \n")
sumtwod = twod + twod1
print(sumtwod)

Sum = 

[[ 3  5  7  9]
 [11 13 15 17]
 [10 12 14 16]]


In [37]:
print(sumtwod.mean(axis=0))
print(sumtwod.mean(axis=1))

[ 8. 10. 12. 14.]
[ 6. 14. 13.]


### Product of two 2d matrices

In [81]:
n = 3 #number of rows and columns
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[9,8,7],[6,5,4],[3,2,1]])

rslt = np.array([[0,0,0],[0,0,0],[0,0,0]])

for i in range (0,n):
    for j in range(0,n):
        for k in range(0,n):
            rslt[i][j] += arr1[i][k]*arr2[k][j]
            # print(rslt[i][j])

print(rslt)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


### Ridership example

In [16]:
ridership = np.array([[0,0,2,5,0],[1478,3877,3674,2328,2539],[1613,4088,3991,6461,2691],[1560,3392,3826,4787,2613]])
print(ridership)

[[   0    0    2    5    0]
 [1478 3877 3674 2328 2539]
 [1613 4088 3991 6461 2691]
 [1560 3392 3826 4787 2613]]


In [38]:
def mean_riders_for_max_station(ridership):
    overall_mean = ridership.mean()
    max_station_first_day = ridership[0,:].argmax()
    print(max_station_first_day)
    mean_for_max = ridership[:,max_station_first_day].mean()
    print(mean_for_max)
    return(overall_mean,mean_for_max)
print(mean_riders_for_max_station(ridership))

3
3395.25
(2446.25, 3395.25)


### Reshaping

In [63]:
a = np.arange(6).reshape(2,3)
# Makes an one dimensional array of numbers from 0 to 5 then it reshapes it to make a 2X3 matrix
print(a)
print(a+10) #adding 10 with the matrix

[[0 1 2]
 [3 4 5]]
[[10 11 12]
 [13 14 15]]


In [70]:
np.argmax(a) # max element in the array

array([1, 1, 1], dtype=int64)

In [72]:
np.argmax(a,axis = 0) # max element of each column

array([1, 1, 1], dtype=int64)

In [74]:
np.argmax(a,axis = 1) # max element of each row

array([2, 2], dtype=int64)

### Numpy Datatype

In [93]:
print(np.array([1,2,3]).dtype)

int32
